sudo: required
language: ruby
rvm:
  - 2.4.0
before_install:
  - gem install bundler -v 1.14.4

addons:
  apt:
    packages:
      - ruby2.0-tcltk
      - libtcl-8.5
      - libtk-8.5

script:
  - ruby2.0 -r tcl
